version: "3.8"

services:
  server:
    build:
      context: ./server
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=${MONGO_URI}

  client:
    build:
      context: ./client
    ports:
      - "3001:3000"
    environment:
      - VITE_API_URL=${VITE_API_URL}

  mongodb:
    image: mongo:latest
    volumes:
      - ./data:/data/db
      - ./mongodb/scripts:/docker-entrypoint-initdb.d
