version: "3.8"

services:
  server:
    build:
      context: ./server
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=${MONGO_URI}

  client:
    build:
      context: ./client
      args:
        VITE_API_URL: ${VITE_API_URL}
    ports:
      - "3001:3000"

  mongodb:
    image: mongo:latest
    volumes:
      - ./data:/data/db
      - ./scripts/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh

  nginx:
    image: nginx:latest
    environment:
      - SERVER_URL=${SERVER_URL}
      - CLIENT_URL=${CLIENT_URL}
      - DOMAIN=${DOMAIN}
    volumes:
      - ./nginx/default.template:/etc/nginx/conf.d/default.template
      - ./scripts/start-nginx.sh:/start-nginx.sh
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/live/:/etc/nginx/ssl/live/:ro
    entrypoint: /bin/sh -c "/start-nginx.sh"
    ports:
      - 80:80
      - 443:443

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/
      - ./certbot/conf/:/etc/letsencrypt/
