version: "3.8"

services:
  server:
    build:
      context: ./server
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=${MONGO_URI}

  client:
    build:
      context: ./client
      args:
        VITE_API_URL: ${VITE_API_URL}
    ports:
      - "3001:3000"

  mongodb:
    image: mongo:latest
    volumes:
      - ./data:/data/db
      - ./mongodb/scripts:/docker-entrypoint-initdb.d

  nginx:
    image: nginx:latest
    environment:
      - SERVER_URL=${SERVER_URL}
      - CLIENT_URL=${CLIENT_URL}
    volumes:
      - ./nginx/default.template:/etc/nginx/conf.d/default.template
      - ./nginx/start.sh:/start.sh
      - ./certbot/www/:/var/www/certbot/:ro
    entrypoint: /bin/sh -c "/start.sh"
    ports:
      - 80:80
      - 8080:8080

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/
      - ./certbot/conf/:/etc/letsencrypt/
